import Vue from "vue/dist/vue.js";

import WgDescExample from "./wg-desc-example/wg-desc-example.vue";
Vue.component("wg-desc-example", WgDescExample);
import WgSlider from "./wg-slider/wg-slider.vue";
Vue.component("wg-slider", WgSlider);
import WgSliderNavig from "./wg-slider/wg-slider-navig.vue";
Vue.component("wg-slider-navig", WgSliderNavig);
import WgSliderZoom from "./wg-slider/wg-slider-zoom.vue";
Vue.component("wg-slider-zoom", WgSliderZoom);
import WgCardAd from "./wg-cards/wg-card-ad.vue";
Vue.component("wg-card-ad", WgCardAd);
import WgCardUsers from "./wg-cards/wg-card-users.vue";
Vue.component("wg-card-users", WgCardUsers);
import WgCardPost from "./wg-cards/wg-card-post.vue";
Vue.component("wg-card-post", WgCardPost);
import WgCardPhoto from "./wg-cards/wg-card-photo.vue";
Vue.component("wg-card-photo", WgCardPhoto);
import WgComments from "./wg-comments/wg-comments.vue";
Vue.component("wg-comments", WgComments);
import WgComment from "./wg-comments/wg-comment.vue";
Vue.component("wg-comment", WgComment);
import WgFilterAdd from "./wg-filters/wg-filter-add.vue";
Vue.component("wg-filter-add", WgFilterAdd);
import WgFormAdd from "./wg-forms/wg-form-add.vue";
Vue.component("wg-form-add", WgFormAdd);
import WgFormPhotos from "./wg-forms/wg-form-photos.vue";
Vue.component("wg-form-photos", WgFormPhotos);
import WgCaptcha from "./wg-captcha/wg-captcha.vue";
Vue.component("wg-captcha", WgCaptcha);
import WgSelectLocation from "./wg-select-location/wg-select-location.vue";
Vue.component("wg-select-location", WgSelectLocation);
import WgMultipleLocation from "./wg-multiple-location/wg-multiple-location.vue";
Vue.component("wg-multiple-location", WgMultipleLocation);
import WgMultipleTransport from "./wg-multiple-transport/wg-multiple-transport.vue";
Vue.component("wg-multiple-transport", WgMultipleTransport);
import WgMessanger from "./wg-messanger/wg-messanger.vue";
Vue.component("wg-messanger", WgMessanger);
import WgSmiles from "./wg-smiles/wg-smiles.vue";
Vue.component("wg-smiles", WgSmiles);
import WgFrameFriends from "./wg-frams/wg-frame-friends.vue";
Vue.component("wg-frame-friends", WgFrameFriends);
