CREATE TABLE "ads" (
    id bigserial,
    name varchar(64) NOT NULL,
    user_id bigint NOT NULL,
    settlements_id smallint NOT NULL,
    model_id smallint NOT NULL,
    body_id smallint NOT NULL,
    drive_id smallint NOT NULL,
    wheel_id smallint NOT NULL,
    fuel_id smallint NOT NULL,
    engin_volume smallint NOT NULL,
    engin_power smallint NOT NULL,
    year smallint NOT NULL,
    run integer NOT NULL,
    photos jsonb NULL,
    price money NOT NULL,
    PRIMARY KEY (id),
    FOREIGN KEY (settlements_id) REFERENCES locations_settlements(id),
    FOREIGN KEY (model_id) REFERENCES transports_models(id),
    FOREIGN KEY (body_id) REFERENCES transports_bodies(id),
    FOREIGN KEY (drive_id) REFERENCES transports_drives(id),
    FOREIGN KEY (wheel_id) REFERENCES transports_wheels(id),
    FOREIGN KEY (fuel_id) REFERENCES transports_fuels(id)
);